"""trails trailforks column

Revision ID: 2556f269b22b
Revises: 2c2fee5876e0
Create Date: 2019-12-15 19:50:57.246551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2556f269b22b'
down_revision = '2c2fee5876e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trails', sa.Column('trailforks', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trails', 'trailforks')
    # ### end Alembic commands ###
