"""status add active and reported

Revision ID: 4b1cce66e293
Revises: 626becf9e5b6
Create Date: 2019-12-15 14:15:49.627684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1cce66e293'
down_revision = '626becf9e5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('status', sa.Column('reported', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'reported')
    op.drop_column('status', 'active')
    # ### end Alembic commands ###
