"""status no id nulls

Revision ID: 59820cbed4a4
Revises: 7f17e8d46069
Create Date: 2019-12-17 13:51:52.150000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59820cbed4a4'
down_revision = '7f17e8d46069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status', 'trail_system',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('status', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('status', 'trail_system',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
