"""change province to select field

Revision ID: 86c852e0488e
Revises: 9129bb549654
Create Date: 2019-12-07 18:25:51.766000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c852e0488e'
down_revision = '9129bb549654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trails', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trails', 'approved')
    # ### end Alembic commands ###
