"""updated all models

Revision ID: bfa919af84b3
Revises: a4a9287cdf23
Create Date: 2019-12-07 15:42:55.015000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa919af84b3'
down_revision = 'a4a9287cdf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trails', sa.Column('province', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trails', 'province')
    # ### end Alembic commands ###
